name: Docker Image CI

on:
  push:
    branches: [ "main", "vault-pg"]
    paths-ignore:
      - 'README.md'
      - 'www-data/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    -
        name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: fra.ocir.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.AUTH_TOKEN }}
    - name: Build and Push the Docker images to OCIR
      run: |
        cd cars-api-100
        docker build . --build-arg APIGW_PATH=/api-100 -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:1.0.0-free
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:1.0.0-free
        cd ..
        cd cars-api-200
        docker build . --build-arg APIGW_PATH=/api-200 -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:2.0.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:2.0.0
        cd ..
        cd cars-api-300-pg
        docker build . --build-arg APIGW_PATH=/api-300 -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:3.0.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/cars-api:3.0.0
        cd ..
        cd ci-sidecar
        docker build . -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-sidecar:1.0.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-sidecar:1.0.0
        cd ..
        cd ci-sidecar-vault
        docker build . -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-sidecar-vault:1.0.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-sidecar-vault:1.0.0
        cd ..
        cd fn-authorizer
        docker build . -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/fn-basicauth:1.1.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/fn-basicauth:1.1.0
    -
          name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
    - name: Build with Maven
      run: |
        cd ci-signup-web
        mvn clean package
        docker build . -t fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-signup-web:1.0.0
        docker push -q fra.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/ci-signup-web:1.0.0
